# Generated by Django 3.1.2 on 2020-12-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0003_auto_20201211_0045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoices',
            new_name='Invoice',
        ),
    ]
