# Generated by Django 3.1.2 on 2020-12-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0004_auto_20201211_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.AutoField(default='SOME STRING', primary_key=True, serialize=False),
        ),
    ]
