# Generated by Django 3.1.2 on 2020-12-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0005_auto_20201211_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
